### ISSUE TITLE
Compiling for windows (under mingw64) - src/time_gist.c:497:44: error: incompatible type for argument 2 of 'period_cmp_bounds'

### ISSUE THREAD

**Issue by robe2** [MobilityDB/MobilityDB#16]
I'm making some progress getting a windows build after fiddling with the CMakeLists.txt file a bit.  I got this far and not sure what is causing these errors
I tried with both PG 11 and PG 12 and got stuck at the same spot.

Any thoughts on how to fix - 
```
-- Found PostgreSQL: C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/lib/libpq.dll (found version "11.2")
Found 110000
-- WIN32=1
Found compatible 110000 include C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include;C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include/server
Found compatible 11.2
Found share C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/share lib C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/lib
-- Found LWGEOM at C:/ming64gcc81/projects/postgis/liblwgeom-2.5w64gcc81/lib/liblwgeom.dll.a include C:/ming64gcc81/projects/postgis/liblwgeom-2.5w64gcc81/include - compiling with PostGIS support
-- Found GSL at C:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/libgsl.dll.a, Found GSLCBLAS at C:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/libgslcblas.dll.a
-- Configuring done
-- Generating done
-- Build files have been written to: C:/ming64gcc81/projects/mobility/MobilityDB/build
Scanning dependencies of target sqlscript
[  1%] Generating mobilitydb--1.0-alpha1.sql.c
[  3%] Generating mobilitydb--1.0-alpha1.sql
[  3%] Built target sqlscript
Scanning dependencies of target control
[  5%] Generating mobilitydb.control
[  5%] Built target control
Scanning dependencies of target MobilityDB
[  6%] Building C object CMakeFiles/MobilityDB.dir/src/doublen.c.obj
[  8%] Building C object CMakeFiles/MobilityDB.dir/src/debug/indexesstat.c.obj
[ 10%] Building C object CMakeFiles/MobilityDB.dir/src/lifting.c.obj
[ 11%] Building C object CMakeFiles/MobilityDB.dir/src/oidcache.c.obj
C:/ming64gcc81/projects/mobility/MobilityDB/src/oidcache.c: In function 'populate_oidcache':
C:/ming64gcc81/projects/mobility/MobilityDB/src/oidcache.c:155:3: warning: implicit declaration of function 'bzero' [-Wimplicit-function-declaration]
   bzero(_op_oids, sizeof(_op_oids));
   ^~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/oidcache.c:155:3: warning: incompatible implicit declaration of built-in function 'bzero'
[ 13%] Building C object CMakeFiles/MobilityDB.dir/src/period.c.obj
[ 15%] Building C object CMakeFiles/MobilityDB.dir/src/periodset.c.obj
[ 16%] Building C object CMakeFiles/MobilityDB.dir/src/rangetypes_ext.c.obj
[ 18%] Building C object CMakeFiles/MobilityDB.dir/src/tbox.c.obj
[ 20%] Building C object CMakeFiles/MobilityDB.dir/src/temporal.c.obj
[ 22%] Building C object CMakeFiles/MobilityDB.dir/src/temporali.c.obj
[ 23%] Building C object CMakeFiles/MobilityDB.dir/src/temporalinst.c.obj
[ 25%] Building C object CMakeFiles/MobilityDB.dir/src/temporals.c.obj
[ 27%] Building C object CMakeFiles/MobilityDB.dir/src/temporalseq.c.obj
[ 28%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_aggfuncs.c.obj
C:/ming64gcc81/projects/mobility/MobilityDB/src/temporal_aggfuncs.c: In function 'random_level':
C:/ming64gcc81/projects/mobility/MobilityDB/src/temporal_aggfuncs.c:201:9: warning: implicit declaration of function 'ffsl' [-Wimplicit-function-declaration]
  return ffsl(~(random() & ((1l << SKIPLIST_MAXLEVEL) - 1)));
         ^~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/temporal_aggfuncs.c:201:32: warning: left shift count >= width of type [-Wshift-count-overflow]
  return ffsl(~(random() & ((1l << SKIPLIST_MAXLEVEL) - 1)));
                                ^~
[ 30%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_analyze.c.obj
[ 32%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_boolops.c.obj
[ 33%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_boxops.c.obj
[ 35%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_compops.c.obj
[ 37%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_gist.c.obj
[ 38%] Building C object CMakeFiles/MobilityDB.dir/src/tnumber_mathfuncs.c.obj
[ 40%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_parser.c.obj
[ 42%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_posops.c.obj
[ 44%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_selfuncs.c.obj
[ 45%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_spgist.c.obj
[ 47%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_textfuncs.c.obj
[ 49%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_util.c.obj
[ 50%] Building C object CMakeFiles/MobilityDB.dir/src/temporal_waggfuncs.c.obj
[ 52%] Building C object CMakeFiles/MobilityDB.dir/src/timeops.c.obj
[ 54%] Building C object CMakeFiles/MobilityDB.dir/src/timestampset.c.obj
[ 55%] Building C object CMakeFiles/MobilityDB.dir/src/time_analyze.c.obj
[ 57%] Building C object CMakeFiles/MobilityDB.dir/src/time_gist.c.obj
In file included from C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include/server/postgres.h:46,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/include/time_gist.h:16,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:14:
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c: In function 'gist_period_double_sorting_split':
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:497:44: error: incompatible type for argument 2 of 'period_cmp_bounds'
    Assert(period_cmp_bounds(&lower, context.right_lower) >= 0);
                                     ~~~~~~~^~~~~~~~~~~~
C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:497:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(&lower, context.right_lower) >= 0);
    ^~~~~~
In file included from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:21:
C:/ming64gcc81/projects/mobility/MobilityDB/include/period.h:83:75: note: expected 'const PeriodBound *' {aka 'const struct <anonymous> *'} but argument is of type 'PeriodBound' {aka 'struct <anonymous>'}
 extern int period_cmp_bounds(const PeriodBound *lower, const PeriodBound *upper);
                                                        ~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:484: CMakeFiles/MobilityDB.dir/src/time_gist.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:954: CMakeFiles/MobilityDB.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
[  3%] Built target sqlscript
[  5%] Built target control
[  6%] Building C object CMakeFiles/MobilityDB.dir/src/time_gist.c.obj
In file included from C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include/server/postgres.h:46,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/include/time_gist.h:16,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:14:
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c: In function 'gist_period_double_sorting_split':
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:497:44: error: incompatible type for argument 2 of 'period_cmp_bounds'
    Assert(period_cmp_bounds(&lower, context.right_lower) >= 0);
                                     ~~~~~~~^~~~~~~~~~~~
C:/ming64gcc81/projects/postgresql/rel/pg11w64gcc81/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:497:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(&lower, context.right_lower) >= 0);
    ^~~~~~
In file included from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:21:
C:/ming64gcc81/projects/mobility/MobilityDB/include/period.h:83:75: note: expected 'const PeriodBound *' {aka 'const struct <anonymous> *'} but argument is of type 'PeriodBound' {aka 'struct <anonymous>'}
 extern int period_cmp_bounds(const PeriodBound *lower, const PeriodBound *upper);
                                                        ~~~~~~~~~~~~~~~~~~~^~~~~
make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:484: CMakeFiles/MobilityDB.dir/src/time_gist.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:954: CMakeFiles/MobilityDB.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

**Comment by chaitan94** [comment]
Looks like it should be

`Assert(period_cmp_bounds(&lower, &context.right_lower) >= 0);`

instead of 

`Assert(period_cmp_bounds(&lower, context.right_lower) >= 0);`

(Basically, an address operator `&` is missing)

@robe2 can you try making this change in line 497 of `time_gist.c` and confirm if it works? If so probably this can be applied to main codebase as well.

**Comment by estebanzimanyi** [comment]
I corrected all the similar error in the sources. I am currently doing the regression tests. After they pass a new version will arrive at the master branch.

**Comment by robe2** [comment]
Okay got further after making those changes.  Now battling linker issues.  I'm guessing it can't find my postgresql lib and liblwgeom lib files for some reason:

> CMakeFiles/MobilityDB.dir/objects.a(temporalseq.c.obj):temporalseq.c:(.text+0xaa49): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(temporalseq.c.obj):temporalseq.c:(.text+0xab5a): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(temporalseq.c.obj):temporalseq.c:(.text+0xabd0): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(temporalseq.c.obj):temporalseq.c:(.text+0xacd1): undefined reference to `palloc'
> CMakeFiles/MobilityDB.dir/objects.a(temporalseq.c.obj):temporalseq.c:(.text+0xad57): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7030): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x705e): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7072): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x70d9): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x70f3): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7137): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x714b): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x71ad): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x71c7): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x721a): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7234): undefined reference to `pfree'
>  : 
>  : 
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7262): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7276): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x72d8): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x72f2): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7345): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x735f): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x738d): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x73a1): undefined reference to `pg_detoast_datum'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x741d): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.text+0x7437): undefined reference to `pfree'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.buffer[.refptr.buffer]+0x0): undefined reference to `buffer'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.LWGEOM_isempty[.refptr.LWGEOM_isempty]+0x0): undefined reference to `LWGEOM_isempty'

**Comment by estebanzimanyi** [comment]
Dear Regina, Is there anything we still need to do in this respect ?

**Comment by robe2** [comment]
Haven't had time to revisit yet. I'll try to in coming week.  I think though the PostgreSQL detection logic  in CMake needs some work.  I'll try to provide a patch once I figure out all the bits missing.

**Comment by robe2** [comment]
Still having problems compiling -- I submitted a pull request of changes I needed to make to get cmake configure to pass.
Is there a reason we are now forcing PostgreSQL 11? Before I was able to at least get to same point with 12.  I can do that again by changing the minimum to 12.

I am now back to -- 

```
[ 58%] Building C object CMakeFiles/MobilityDB.dir/src/time_gist.c.obj
In file included from C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/postgres.h:46,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/include/time_gist.h:16,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:14:
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c: In function 'gist_period_double_sorting_split':
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:63: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
                                                               ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:483:30: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
     true, context.right_lower->lower, period->lower_inc,
                              ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:484:24: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
     context.right_lower->inclusive) >= 0);
                        ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:503: CMakeFiles/MobilityDB.dir/src/time_gist.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:965: CMakeFiles/MobilityDB.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
[  1%] Built target sqlscript
[  3%] Built target control
[  5%] Building C object CMakeFiles/MobilityDB.dir/src/time_gist.c.obj
In file included from C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/postgres.h:46,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/include/time_gist.h:16,
                 from C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:14:
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c: In function 'gist_period_double_sorting_split':
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:63: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
                                                               ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:483:30: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
     true, context.right_lower->lower, period->lower_inc,
                              ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:484:24: error: invalid type argument of '->' (have 'PeriodBound' {aka 'struct <anonymous>'})
     context.right_lower->inclusive) >= 0);
                        ^~
C:/MING64~1/projects/POSTGR~1/rel/PG11W6~1/include/server/c.h:724:7: note: in definition of macro 'Trap'
   if (condition) \
       ^~~~~~~~~
C:/ming64gcc81/projects/mobility/MobilityDB/src/time_gist.c:482:4: note: in expansion of macro 'Assert'
    Assert(period_cmp_bounds(period->lower, context.right_lower->val,
    ^~~~~~
make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:503: CMakeFiles/MobilityDB.dir/src/time_gist.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:965: CMakeFiles/MobilityDB.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
make: *** No rule to make target 'installcheck'.  Stop.

```

So I guess those fixes @chaitan94  was going to commit were never comitted or I'm looking at the wrong branch.  I'll try repatching again.  I recall the changes mentioned got me past that point.

**Comment by estebanzimanyi** [comment]
Dear Regina

Could you please try with the develop branch ? There the version 12 of
Postgresql is allowed.

Let me know how it goes so I can help you.

**Comment by robe2** [comment]
The good news is the develop branch is able to pick up all the includes from my PATH variable so guess my pull request may not be needed.

I have additional problems though:

```
> Found 120000
> -- WIN32=1
> Found compatible 120000 include C:/ming64gcc81/projects/postgresql/rel/pg12w64gcc81/include;C:/ming64gcc81/projects/postgresql/rel/pg12w64gcc81/include/server
> -- PostgreSQL LINK_DIRECTORIES = C:/ming64gcc81/projects/postgresql/rel/pg12w64gcc81/lib
> Found compatible 12.2
> Found share C:/MING64~1/projects/POSTGR~1/rel/PG12W6~4/share lib C:/MING64~1/projects/POSTGR~1/rel/PG12W6~4/lib
> -- Found LWGEOM at C:/ming64gcc81/projects/postgis/liblwgeom-2.5w64gcc81/lib/liblwgeom.dll.a include C:/ming64gcc81/projects/postgis/liblwgeom-2.5w64gcc81/include - compiling with PostGIS support
> CMake Error at CMakeLists.txt:194 (include):
>   include could not find load file:
> 
>     test/scripts/test.cmake
> 
> 
> CMake Error at CMakeLists.txt:197 (include):
>   include could not find load file:
> 
>     point/point.cmake
> 
> 
> -- Found GSL at C:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/libgsl.dll.a, Found GSLCBLAS at C:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/libgslcblas.dll.a
> -- GSL INclude=C:/ming64gcc81/projects/gsl/rel-gsl-2.6/include
> -- Configuring incomplete, errors occurred!
> See also "C:/ming64gcc81/projects/mobility/MobilityDB/CMakeFiles/CMakeOutput.log".
> make: *** No targets specified and no makefile found.  Stop.
> make: *** No rule to make target 'install'.  Stop.
> make: *** No rule to make target 'installcheck'.  Stop.
> 

```

I'm guessing maybe cause I'm building in a subfolder.
My build script looks like this

```
mkdir MobilityDb/build
cd MobilityDB/build
cmake  -G "MSYS Makefiles"  ..
```

**Comment by robe2** [comment]
Disregard my last note -- guess it was picking up files still in CMakefiles folder.  Clearing that out I'm back to no detection.

**Comment by robe2** [comment]
making some progress, got past the postgresql linker errors with some cmake changes.  Now battling liblwgeom linker errors.

> [100%] Linking C shared module libMobilityDB.dll
> CMakeFiles/MobilityDB.dir/objects.a(tinstant.c.obj):tinstant.c:(.rdata$.refptr.lwgeom_hash[.refptr.lwgeom_hash]+0x0): undefined reference to `lwgeom_hash'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_aggfuncs.c.obj):temporal_aggfuncs.c:(.text+0x9c2): undefined reference to `ffsl'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_util.c.obj):temporal_util.c:(.rdata$.refptr.geography_lt[.refptr.geography_lt]+0x0): undefined reference to `geography_lt'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_util.c.obj):temporal_util.c:(.rdata$.refptr.lwgeom_lt[.refptr.lwgeom_lt]+0x0): undefined reference to `lwgeom_lt'
> CMakeFiles/MobilityDB.dir/objects.a(stbox.c.obj):stbox.c:(.rdata$.refptr.transform[.refptr.transform]+0x0): undefined reference to `transform'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_shortestline2d[.refptr.LWGEOM_shortestline2d]+0x0): undefined reference to `LWGEOM_shortestline2d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_shortestline3d[.refptr.LWGEOM_shortestline3d]+0x0): undefined reference to `LWGEOM_shortestline3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_set_srid[.refptr.LWGEOM_set_srid]+0x0): undefined reference to `LWGEOM_set_srid'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.BOX2D_to_LWGEOM[.refptr.BOX2D_to_LWGEOM]+0x0): undefined reference to `BOX2D_to_LWGEOM'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.BOX3D_to_LWGEOM[.refptr.BOX3D_to_LWGEOM]+0x0): undefined reference to `BOX3D_to_LWGEOM'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.intersection[.refptr.intersection]+0x0): undefined reference to `intersection'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.intersects[.refptr.intersects]+0x0): undefined reference to `intersects'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_azimuth[.refptr.geography_azimuth]+0x0): undefined reference to `geography_azimuth'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_length[.refptr.geography_length]+0x0): undefined reference to `geography_length'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_length_linestring[.refptr.LWGEOM_length_linestring]+0x0): undefined reference to `LWGEOM_length_linestring'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_addpoint[.refptr.LWGEOM_addpoint]+0x0): undefined reference to `LWGEOM_addpoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_setpoint_linestring[.refptr.LWGEOM_setpoint_linestring]+0x0): undefined reference to `LWGEOM_setpoint_linestring'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_from_geometry[.refptr.geography_from_geometry]+0x0): undefined reference to `geography_from_geometry'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geometry_from_geography[.refptr.geometry_from_geography]+0x0): undefined reference to `geometry_from_geography'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_dwithin[.refptr.geography_dwithin]+0x0): undefined reference to `geography_dwithin'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_distance[.refptr.geography_distance]+0x0): undefined reference to `geography_distance'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_covers[.refptr.geography_covers]+0x0): undefined reference to `geography_covers'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.relate_pattern[.refptr.relate_pattern]+0x0): undefined reference to `relate_pattern'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.relate_full[.refptr.relate_full]+0x0): undefined reference to `relate_full'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.LWGEOM_dwithin3d[.refptr.LWGEOM_dwithin3d]+0x0): undefined reference to `LWGEOM_dwithin3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.LWGEOM_dwithin[.refptr.LWGEOM_dwithin]+0x0): undefined reference to `LWGEOM_dwithin'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.touches[.refptr.touches]+0x0): undefined reference to `touches'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.overlaps[.refptr.overlaps]+0x0): undefined reference to `overlaps'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.intersects3d[.refptr.intersects3d]+0x0): undefined reference to `intersects3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.ST_Equals[.refptr.ST_Equals]+0x0): undefined reference to `ST_Equals'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.disjoint[.refptr.disjoint]+0x0): undefined reference to `disjoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.crosses[.refptr.crosses]+0x0): undefined reference to `crosses'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.coveredby[.refptr.coveredby]+0x0): undefined reference to `coveredby'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.covers[.refptr.covers]+0x0): undefined reference to `covers'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.containsproperly[.refptr.containsproperly]+0x0): undefined reference to `containsproperly'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.contains[.refptr.contains]+0x0): undefined reference to `contains'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_distance.c.obj):tpoint_distance.c:(.rdata$.refptr.distance3d[.refptr.distance3d]+0x0): undefined reference to `distance3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_distance.c.obj):tpoint_distance.c:(.rdata$.refptr.distance[.refptr.distance]+0x0): undefined reference to `distance'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_in.c.obj):tpoint_in.c:(.text+0x1651): undefined reference to `getSRIDbySRS'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_in.c.obj):tpoint_in.c:(.rdata$.refptr.LWGEOM_makepoint[.refptr.LWGEOM_makepoint]+0x0): undefined reference to `LWGEOM_makepoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_out.c.obj):tpoint_out.c:(.text+0x197e): undefined reference to `getSRSbySRID'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_out.c.obj):tpoint_out.c:(.text+0x199b): undefined reference to `getSRSbySRID'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.buffer[.refptr.buffer]+0x0): undefined reference to `buffer'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.LWGEOM_isempty[.refptr.LWGEOM_isempty]+0x0): undefined reference to `LWGEOM_isempty'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:974: libMobilityDB.dll] Error 1
> make[1]: *** [CMakeFiles/Makefile2:965: CMakeFiles/MobilityDB.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2
> [  3%] Built target sqlscript
> [  5%] Built target control
> [  6%] Linking C shared module libMobilityDB.dll
> CMakeFiles/MobilityDB.dir/objects.a(tinstant.c.obj):tinstant.c:(.rdata$.refptr.lwgeom_hash[.refptr.lwgeom_hash]+0x0): undefined reference to `lwgeom_hash'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_aggfuncs.c.obj):temporal_aggfuncs.c:(.text+0x9c2): undefined reference to `ffsl'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_util.c.obj):temporal_util.c:(.rdata$.refptr.geography_lt[.refptr.geography_lt]+0x0): undefined reference to `geography_lt'
> CMakeFiles/MobilityDB.dir/objects.a(temporal_util.c.obj):temporal_util.c:(.rdata$.refptr.lwgeom_lt[.refptr.lwgeom_lt]+0x0): undefined reference to `lwgeom_lt'
> CMakeFiles/MobilityDB.dir/objects.a(stbox.c.obj):stbox.c:(.rdata$.refptr.transform[.refptr.transform]+0x0): undefined reference to `transform'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_shortestline2d[.refptr.LWGEOM_shortestline2d]+0x0): undefined reference to `LWGEOM_shortestline2d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_shortestline3d[.refptr.LWGEOM_shortestline3d]+0x0): undefined reference to `LWGEOM_shortestline3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_set_srid[.refptr.LWGEOM_set_srid]+0x0): undefined reference to `LWGEOM_set_srid'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.BOX2D_to_LWGEOM[.refptr.BOX2D_to_LWGEOM]+0x0): undefined reference to `BOX2D_to_LWGEOM'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.BOX3D_to_LWGEOM[.refptr.BOX3D_to_LWGEOM]+0x0): undefined reference to `BOX3D_to_LWGEOM'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.intersection[.refptr.intersection]+0x0): undefined reference to `intersection'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.intersects[.refptr.intersects]+0x0): undefined reference to `intersects'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_azimuth[.refptr.geography_azimuth]+0x0): undefined reference to `geography_azimuth'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_length[.refptr.geography_length]+0x0): undefined reference to `geography_length'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_length_linestring[.refptr.LWGEOM_length_linestring]+0x0): undefined reference to `LWGEOM_length_linestring'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_addpoint[.refptr.LWGEOM_addpoint]+0x0): undefined reference to `LWGEOM_addpoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.LWGEOM_setpoint_linestring[.refptr.LWGEOM_setpoint_linestring]+0x0): undefined reference to `LWGEOM_setpoint_linestring'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geography_from_geometry[.refptr.geography_from_geometry]+0x0): undefined reference to `geography_from_geometry'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialfuncs.c.obj):tpoint_spatialfuncs.c:(.rdata$.refptr.geometry_from_geography[.refptr.geometry_from_geography]+0x0): undefined reference to `geometry_from_geography'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_dwithin[.refptr.geography_dwithin]+0x0): undefined reference to `geography_dwithin'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_distance[.refptr.geography_distance]+0x0): undefined reference to `geography_distance'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.geography_covers[.refptr.geography_covers]+0x0): undefined reference to `geography_covers'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.relate_pattern[.refptr.relate_pattern]+0x0): undefined reference to `relate_pattern'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.relate_full[.refptr.relate_full]+0x0): undefined reference to `relate_full'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.LWGEOM_dwithin3d[.refptr.LWGEOM_dwithin3d]+0x0): undefined reference to `LWGEOM_dwithin3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.LWGEOM_dwithin[.refptr.LWGEOM_dwithin]+0x0): undefined reference to `LWGEOM_dwithin'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.touches[.refptr.touches]+0x0): undefined reference to `touches'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.overlaps[.refptr.overlaps]+0x0): undefined reference to `overlaps'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.intersects3d[.refptr.intersects3d]+0x0): undefined reference to `intersects3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.ST_Equals[.refptr.ST_Equals]+0x0): undefined reference to `ST_Equals'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.disjoint[.refptr.disjoint]+0x0): undefined reference to `disjoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.crosses[.refptr.crosses]+0x0): undefined reference to `crosses'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.coveredby[.refptr.coveredby]+0x0): undefined reference to `coveredby'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.covers[.refptr.covers]+0x0): undefined reference to `covers'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.containsproperly[.refptr.containsproperly]+0x0): undefined reference to `containsproperly'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_spatialrels.c.obj):tpoint_spatialrels.c:(.rdata$.refptr.contains[.refptr.contains]+0x0): undefined reference to `contains'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_distance.c.obj):tpoint_distance.c:(.rdata$.refptr.distance3d[.refptr.distance3d]+0x0): undefined reference to `distance3d'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_distance.c.obj):tpoint_distance.c:(.rdata$.refptr.distance[.refptr.distance]+0x0): undefined reference to `distance'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_in.c.obj):tpoint_in.c:(.text+0x1651): undefined reference to `getSRIDbySRS'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_in.c.obj):tpoint_in.c:(.rdata$.refptr.LWGEOM_makepoint[.refptr.LWGEOM_makepoint]+0x0): undefined reference to `LWGEOM_makepoint'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_out.c.obj):tpoint_out.c:(.text+0x197e): undefined reference to `getSRSbySRID'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_out.c.obj):tpoint_out.c:(.text+0x199b): undefined reference to `getSRSbySRID'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.buffer[.refptr.buffer]+0x0): undefined reference to `buffer'
> CMakeFiles/MobilityDB.dir/objects.a(tpoint_tempspatialrels.c.obj):tpoint_tempspatialrels.c:(.rdata$.refptr.LWGEOM_isempty[.refptr.LWGEOM_isempty]+0x0): undefined reference to `LWGEOM_isempty'
> collect2.exe: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/MobilityDB.dir/build.make:974: libMobilityDB.dll] Error 1
> make[1]: *** [CMakeFiles/Makefile2:965: CMakeFiles/MobilityDB.dir/all] Error 2
> make: *** [Makefile:160: all] Error 2
> make: *** No rule to make target 'installcheck'.  Stop.
>

**Comment by robe2** [comment]
Which library is ffsl defined in.  I've gotten the point where I get a dll now (after hacking the linklibs.rsp and flags.make - I need to back track my steps.

```
 return ffsl(~(random() & ((1l << SKIPLIST_MAXLEVEL) - 1)));

```

But I get an undefined reference to ffsl unless I remark out the line in temporal_agg_funcs.c and return an arbitrary number .  I thought maybe it was in gsl lib but that lib is included in my linklibs.rsp.

**Comment by robe2** [comment]
Should the mobility library depend on both liblwgeom-2.5 and postgis-2.5.

The only way I could get it to compile was to include both and because of the linking issues, I had to add in all the liblwgeom dependencies.

So my build\CMakeFiles\MobilityDB.dir\linklibs.rsp

looks like this:

>   -LC:/ming64gcc81/projects/postgresql/rel/pg12w64gcc81/lib -LC:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/ -LC:/ming64gcc81/projects/geos/rel-3.8w64gcc81/lib -lgeos -lgeos_c -lpthread -L/projects/json-c/rel-0.12w64gcc81/lib C:/ming64gcc81/projects/json-c/rel-0.12w64gcc81/lib/libjson-c.a -LC:/ming64gcc81/projects/CGAL/rel-sfcgal-1.3.8w64gcc81/lib -lpostgres -lpostgis-2.5 -lliblwgeom-2-5-0 -lgsl C:/ming64gcc81/projects/gsl/rel-gsl-2.6/lib/libgslcblas.a -lgslcblas -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 

But good news I have a working extension and can do 

`CREATE EXTENSION mobilitydb;`

and did some tests with docs creating periods and  seems to work.

Just need a more pleasant compile and ideally not have dependency on both postgis-2.5 and liblwgeom

**Comment by alesuiss** [comment]
Regarding the ffsl() problem: that function is apparently not in mingw64. I've just made a PR to detect its presence and replace it with a dumb version if it's not there.

**Comment by estebanzimanyi** [comment]
Dear Regina ! Many thanks for your efforts and for the great news of having MobilityDB on Windows ! We have been waiting for this moment for such a long time :-)

Alas we don't have experience in this issue of having dependency on either postgis-2.5 or liblwgeom. How the other extensions built on top of PostGIS work ? Could you please suggest a course of action so we can implement it ?

**Comment by estebanzimanyi** [comment]
Actually, we use postgis-2.5.so just to ensure the version, we don't do anything with it. I commented the following lines in the CMakeLists.txt and everything works, the tests pass without any problem.

find_library(HAS_LWGEOM lwgeom)
if (HAS_LWGEOM)
	MESSAGE(STATUS "Found LWGEOM at ${HAS_LWGEOM} - compiling with PostGIS support")
#	if(NOT EXISTS "${PostgreSQL_EXTLIB_DIR}/postgis-2.5.so")
#		message(FATAL_ERROR "Could not find postgis-2.5.so; only PostGIS 2.5 is currently supported")
#	endif()
else()
    message(FATAL_ERROR "Could not find lwgeom; ")
endif ()

**Comment by robe2** [comment]
For some reason I had to explicitly include postgis-2.5 in the final make script for it to compile.  I'll revisit.
Let me try recompiling with the other changes you have made to see how much that fixes.

What I had seen in dependency walker in windows

![image](https://user-images.githubusercontent.com/4734450/90698990-238e2280-e250-11ea-81fa-93bed487c5ea.png)


Regarding your question about how the PostGIS extensions are built.  Each extension has it's own copy of liblwgeom.  liblwgeom is statically linked in each one.  I wanted to do the same with MobilityDb, but couldn't get the static linking to work.

So for example dependency walker for postgis-2.5.dll looks like below.  postgis-sfcgal extension is a bit of an odd-duck as it for historical reasons was packaged as part of postgis lib so that the GUC back-end switch could be used as there was some overlap with geos and sfcgal functions.  Hoping to spin it out as it's own library in 3.1 since we got rid of the GUC postgis.backend so that siamese twin binding is no longer needed.

![image](https://user-images.githubusercontent.com/4734450/90699129-7ff14200-e250-11ea-890c-24fca7b18262.png)


rtpostgis-2.5  looks like this:

![image](https://user-images.githubusercontent.com/4734450/90699257-d0689f80-e250-11ea-8cc9-4fcf6c03c39e.png)


So you see there is no direct dependency shown on liblwgeom because it's statically linked in.

BTW I did get a crash on a function in the manual - https://docs.mobilitydb.com/MobilityDB/master/ch03.html#examples_temporal_types

The second example worked perfectly.  The first one crashed the backend on this query:

```
SELECT tsum(NoEmps)
FROM Department;
```

I had @cvvergara try it and did not crash on her so I chalked it up to a windows issues. I forgot I was also building against an unreleased postgis-2.5 (that which became 2.5.5) so could also be that that we changed the liblwgeom api in 2.5.5.  That was one of the reasons we didn't want liblwgeom shared because then we would have to be careful about when we change it and announce such change by bumping the number.

**Comment by estebanzimanyi** [comment]
The latest version of the develop branch compiles with MinGW.

Is this issue still needed ?

**Comment by robe2** [comment]
Yes you can close this out.
