### ISSUE TITLE
undefined symbol: meos_basetype while "CREATE EXTENSION"

### ISSUE THREAD

**Issue by galitus** [MobilityDB/MobilityDB#570]
**Describe the bug**
could not load library "/usr/lib64/postgresql-14/lib64/libMobilityDB-1.1.so": /usr/lib64/postgresql-14/lib64/libMobilityDB-1.1.so: undefined symbol: meos_basetype

**To Reproduce**
1. CREATE EXTENSION mobilitydb;

**Expected behavior**
Successful activated extension for the used db.

**Additional context**
I compiled the version 1.1.1 from source tarball on gentoo linux.
Compilation didn't fail.

```
-- Including network points
-- The C compiler identification is GNU 13.2.1
-- The CXX compiler identification is GNU 13.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building MobilityDB version 1.1.1
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Compiling into position-independent code (PIC)
-- Looking for ffsl
-- Looking for ffsl - found
-- LITTLE_ENDIAN
-- Looking for strchrnul
-- Looking for strchrnul - found
-- Looking for __get_cpuid
-- Looking for __get_cpuid - found
-- Performing Test HAVE_X86_64_POPCNTQ
-- Performing Test HAVE_X86_64_POPCNTQ - Success
CMake Warning (dev) at cmake/FindGEOS.cmake:102 (EXEC_PROGRAM):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/FindGEOS.cmake:113 (EXEC_PROGRAM):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/FindGEOS.cmake:125 (EXEC_PROGRAM):
  Policy CMP0153 is not set: The exec_program command should not be called.
  Run "cmake --help-policy CMP0153" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  Use execute_process() instead.
Call Stack (most recent call first):
  CMakeLists.txt:214 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found GEOS: /usr/lib64/libgeos_c.so (3.11.2)
-- GEOS_INCLUDE_DIR: /usr/include
-- GEOS_LIBRARY: /usr/lib64/libgeos_c.so
-- GEOS_VERSION: 3.11.2
-- GEOS_VERSION_MAJOR: 3
-- GEOS_VERSION_MINOR: 11
-- POSTGIS_GEOS_VERSION: 41
-- Found PROJ: /usr/include (found version "(9.2.1)") 
-- Found PROJ: /usr/lib64/libproj.so (9.2.1)
-- PROJ_INCLUDE_DIRS: /usr/include
-- POSTGIS_PROJ_VERSION: 92
-- Found JSON-C: /usr/include/json-c  
-- JSON-C_INCLUDE_DIRS: /usr/include/json-c
-- JSON-C_LIBRARIES: /lib64/libjson-c.so
-- Found GSL: /usr/include (found version "2.7.1") 
-- GSL_VERSION: 2.7.1
-- -------------------
-- Building MobilityDB
-- -------------------
-- POSTGRESQL_VERSION_MAJOR=14
-- POSTGRESQL_VERSION_MINOR=12
-- POSTGRESQL_BIN_DIR: /usr/lib64/postgresql-14/bin
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql-14/server
-- POSTGRESQL_LIBRARIES: /usr/lib64/postgresql-14/lib64
-- POSTGRESQL_SHARE_DIR: /usr/share/postgresql-14
-- POSTGRESQL_DYNLIB_DIR: /usr/lib64/postgresql-14/lib64
-- POSTGRESQL_VERSION: 14.12
-- POSTGRESQL_VERSION_NUMBER: 141200
-- POSTGRESQL_VERSION_STRING: PostgreSQL 14.12
-- POSTGIS_PGSQL_VERSION: 140
-- Found POSTGRESQL: /usr/lib64/postgresql-14/bin (found suitable version "14.12", minimum required is "12") 
-- Looking for postgis.control file in /usr/share/postgresql-14/extension
-- Found POSTGIS: /usr/lib64/postgresql-14/lib64/postgis-3.so (found version "3.3.2") 
-- POSTGRESQL_SHARE_DIR: /usr/share/postgresql-14
-- POSTGRESQL_DYNLIB_DIR: /usr/lib64/postgresql-14/lib64
-- POSTGIS_LIBRARY: /usr/lib64/postgresql-14/lib64/postgis-3.so
-- POSTGIS_CONTROL: /usr/share/postgresql-14/extension/postgis.control
-- POSTGIS_VERSION: 3.3.2
-- POSTGIS_VERSION_STR: PostGIS 3.3.2
-- POSTGIS_VERSION_NUMBER: 30302
-- Including network points
-- Including SQL definitions and tests
-- Library name extension: '.so'
-- Substitution: /var/tmp/portage/dev-db/MobilityDB-1.1.1/work/MobilityDB-1.1.1_build-14/libMobilityDB-1.1.so
-- Found Xz: /usr/bin/xz  
-- XZ_EXECUTABLE: /usr/bin/xz
-- XZCAT_EXECUTABLE: /usr/bin/xzcat
Enabling test 003_span_pg13
Enabling test 007_spanset_pg14
Enabling test 007_spanset_tbl_pg14
-- PROJECT_DOC_TARGETS = 
-- PROJECT_BUILD_LANGUAGES = en
-- PROJECT_BUILD_LANGUAGES_STRING = English
```

Installed files created from my ebuild package:
```
/usr
/usr/lib64
/usr/lib64/postgresql-14
/usr/lib64/postgresql-14/lib64
/usr/lib64/postgresql-14/lib64/libMobilityDB-1.1.so
/usr/share
/usr/share/doc
/usr/share/doc/MobilityDB-1.1.1
/usr/share/doc/MobilityDB-1.1.1/README.md.bz2
/usr/share/postgresql-14
/usr/share/postgresql-14/extension
/usr/share/postgresql-14/extension/mobilitydb--1.1.1.sql
/usr/share/postgresql-14/extension/mobilitydb.control
```

Maybe helpful?:
```
ldd /usr/lib64/postgresql-14/lib64/libMobilityDB-1.1.so
	linux-vdso.so.1 (0x00007ffd9ef7f000)
	libjson-c.so.5 => /usr/lib64/libjson-c.so.5 (0x00007f22c5c5d000)
	libgsl.so.27 => /usr/lib64/libgsl.so.27 (0x00007f22c59a5000)
	libgeos_c.so.1 => /usr/lib64/libgeos_c.so.1 (0x00007f22c5959000)
	libproj.so.25 => /usr/lib64/libproj.so.25 (0x00007f22c557c000)
	libc.so.6 => /usr/lib64/libc.so.6 (0x00007f22c53b5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f22c5f16000)
	libgslcblas.so.0 => /usr/lib64/libgslcblas.so.0 (0x00007f22c5377000)
	libm.so.6 => /usr/lib64/libm.so.6 (0x00007f22c52cb000)
	libgeos.so.3.11.2 => /usr/lib64/libgeos.so.3.11.2 (0x00007f22c502d000)
	libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6 (0x00007f22c4dc6000)
	libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libgcc_s.so.1 (0x00007f22c4da1000)
	libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007f22c4c24000)
	libtiff.so.6 => /usr/lib64/libtiff.so.6 (0x00007f22c4bab000)
	libz.so.1 => /usr/lib64/libz.so.1 (0x00007f22c4b91000)
```

Any idea why do I get this message?
I have seen with cmake -LA that MEOS:BOOL=OFF was selected as OFF.
Is that normal behaviour? 
Should I do more than just cmake .. and build?

Thanks in advance

**Comment by mschoema** [comment]
Hi,

Indeed, MEOS should be OFF when building MobilityDB, this flag is used to compile the [MEOS](https://libmeos.org/)  library on its own.
However, this error is suprising, as `meos_basetype` is only called in Debug build inside asserts.
For this reason, we don't implement the function when building in Release mode (default when calling `cmake ..`).
Could it be that you are somehow compiling without -DNDEBUG while in Release mode?
Anyways, I am preparing a small patch to make this function always available, which should fix the issue.

**Comment by galitus** [comment]
Hey,

thanks for the feedback. 
I found one problem with the gentoo build system, because if not explicitly mentioned
CMAKE_BUILD_TYPE=Release it will build with CMAKE_BUILD_TYPE=RelWithDebInfo .
I fixed this, and it is build now with Release, but the issue persists.

Greetings

**Comment by mschoema** [comment]
We have just merged PR #571 which hopefully fixes the issue.
Could you try to compile and install MobilityDB from the current `master` branch to check if it now works?
If so, we could potentially backport the fix to `stable-1.1` and produce a new patch of 1.1 with the bugfix.

**Comment by galitus** [comment]
Alright, I tried the master branch.
The error for meos_basetype is gone, but now we have undefined symbol: temptype_subtype .

Thanks for your work (so far) : )

**Comment by mschoema** [comment]
I was somewhat expecting this, `temptype_subtype` is another function that is only called in asserts.
I am still not sure why this happens though, as asserts should only be active in Debug mode.
Let me try one last thing and if this doesn't work I'll just remove the `#if` conditions on the code to make all these assert-only functions available at all time.

**Comment by mschoema** [comment]
I just merged PR #578 which uses the `NDEBUG` macro instead of our own `DEBUG_BUILD` macro.
Let me know if this works or not. If not, I'll just make these functions always available.

**Comment by galitus** [comment]
The last commit did the trick. : )

No undefined symbols and a successful creation of this extension in our Postgres db.

Thanks for your effort to make it work!
